import sqlite3


connection = sqlite3.connect("database.sqlite")
cursor= sqlite3.Cursor(connection)


request = ("CREATE TABLE IF NOT  EXISTS brawler"
           "(id INTEGER PRIMARY KEY AUTOINCREMENT,"
           "name VARCHAR(255),"
           "rares VARCHAR(255),"
           "description VARCHAR(255),"
           "hp INTEGER,"
           "yron INTEGER,"
           "build VARCHAR(255)), "
           "hypercharge VARCHAR(255))")
cursor.execute(request)

insert_request = ("INSERT INTO brawler" "(name, rares, description, hp, yron, build, hypercharge) VALUES (?, ?, ?, ?, ?, ?, ?)")

cursor.execute(insert_request, ("Шелли", "common", "Шелли — идеальный рейнджер. Она ответственная, выносливая и непревзойдённо обращается с ружьём, и ей непонятно, как Кольт перетянул всё внимание на себя", "7400", "600", "1.webp,gadget1.webp,yron.webp,dop.webp,Shelly.webp", "yes"))
cursor.execute(insert_request, ("Нита", "rare", "Нита — совсем малышка, но рвётся в бой с недетской яростью! Её шапка в виде плюшевого мишки как бы намекает: не будите спящего медведя", "8000", "1920", "2.png,22.webp,compan.png,yron.webp,Nita.webp", "yes"))
cursor.execute(insert_request, ("Кольт", "rare", "Кольт — настоящая звезда парка Старр! Его стиль, обаяние и трюки с пистолетами покорят любого (за исключением Шелли)", "5600", "720", "3.jpg,33.webp.reload.jpg,dop.webp,colt.webp", "yes"))
cursor.execute(insert_request, ("Булл", "rare", "Булл уже не такой бесшабашный, как в юности, но это ещё не значит, что он не наваляет любому, кто явно напрашивается", "10000", "880", "6.webp,66.webp,dop.webp,dop.webp,zaryad_supera.webp,bull.webp", "yes"))
cursor.execute(insert_request, ("Брок", "rare", "Брок — геймер и тролль. Вообще-то он романтичный интроверт, но ради победы он готов выйти из зоны комфорта", "5400", "2320", "5.webp,55.webp,shit.png,reload.jpg,Brok.webp", "yes"))
cursor.execute(insert_request, ("Эль Примо", "rare", "Эль Примо всегда в центре внимания, и он это просто обожает! Публика в восторге от него, а вот коллеги – не очень", "12000", "760", "4.webp,44.webp,hit.png,yron.webp,el_primo.webp", "yes"))
cursor.execute(insert_request, ("Барли", "rare", "Барли — робот для приготовления напитков и разговоров с посетителями. Он помешан на чистоте, и это сразу поймёт любой, кто прольёт напиток на его барную стойку", "4800", "1600", "8.webp,88.webp,dop.webp,shit.png,Barli.webp", "yes"))
cursor.execute(insert_request, ("Поко", "rare", "Поко верит в чудотворную силу музыки и так любит свою гитару, что ни на минуту не прекращает играть. Даже когда его очень просят", "7400", "1520", "7.webp,77.webp,dop.webp,yron.webp,Poco.webp", "yes"))
cursor.execute(insert_request, ("Роза", "rare", "Роза одинаково увлекается и ботаникой, и боксом. Она обожает свой сад, но если какое-то растение обнаглеет, то получит и по вершкам, и по корешкам", "10000", "920", "9.webp,99.webp,yron.webp,speed.webp,Rosa.webp", "yes"))
cursor.execute(insert_request, ("Джесси", "superrare", "Джесси — изобретательница-вундеркинд. Она мастерит оружие и гаджеты из хлама, чтобы доказать своей матери Пэм, что может постоять за себя", "6000", "2120", "10.webp,1010.webp,dop.webp,compan.png,Jessi.webp", "yes"))
cursor.execute(insert_request, ("Диномайк", "superrare", "Динамайк — старый шахтёр и золотоискатель, который обожает всё взрывать. Ничто не радует его так, как запах дыма и грохот камней!", "5600", "1600", "11.webp,1111.webp,dop.webp,yron.webp,Dino.webp", "yes"))
cursor.execute(insert_request, ("Тик", "superrare", "Тик хвостиком ходит за Пенни и участвует во всех её затеях. Единственное, что он умеет — это взрывать всё вокруг, но другого от него обычно и не требуется", "4400", "1280", "12.webp,1212.webp,dop.webp,tickm.webp,Tic.webp", "yes"))
cursor.execute(insert_request, ("8-бит", "superrare", "8-БИТ — игровой автомат, ненавидящий игроков. Всё потому, что однажды кто-то разозлился из-за проигрыша и украл один из его пистолетов", "10000", "640", "13.webp,1313.webp,dop.webp,yron.webp,Bit.webp", "yes"))
cursor.execute(insert_request, ("Рико", "superrare", "Рико — совершенно точно самый настоящий межгалактический охотник за головами, а не автомат со жвачкой, который пытается круто выглядеть", "5600", "640", "14.webp,1414.webp,dop.webp,reload.jpg,Rico.webp", "yes"))
cursor.execute(insert_request, ("Дэррил", "superrare", "Дэррил пошёл в пираты, потому что устал работать, но теперь ему приходится вкалывать ещё больше, защищая корабль. Какая ирония", "10600", "480", "15.webp,1515.webp,hil.png,yron.webp,derril.webp", "yes"))
cursor.execute(insert_request, ("Пенни", "superrare", "Пенни не разбирается в старых картах и морских легендах. Быть пираткой для неё означает палить из пушек и брать всё, что приглянулось!", "6400", "1960", "16.webp,1616.webp,shit.png,yron.webp,Penni.webp", "yes"))
cursor.execute(insert_request, ("Карл", "superrare", "Карл — робот-шахтёр, который без ума от камней и горных пород, а в последнее время серьёзно увлёкся изучением кристаллов!", "8000", "1480", "17.webp,1717.webp,dop.webp,yron.webp,Carl.webp", "no"))
cursor.execute(insert_request, ("Джеки", "superrare", "Джеки любит рассказывать всякие байки из своей шахтёрской жизни, не стесняясь в выражениях. К счастью, шум отбойного молотка заглушает ругательства", "10000", "2480", "18.webp,1818.webp,hil.png,yron.webp,Jeki.webp", "yes"))
cursor.execute(insert_request, ("Гас", "superrare", "Малыш Гас такой бледный, что его часто принимают за привидение. Впрочем, ему это нравится, ведь он обожает всё жуткое и сверхъестественное", "6400", "2240", "19.webp,1919.webp,dop.webp,yron.webp,Gas.webp", "no"))
cursor.execute(insert_request, ("Бо", "Epic", "Бо уже долгое время выживает в джунглях. Впечатляет, учитывая, что у него при себе нет ничего, кроме игрушек из магазина сувениров", "7200", "1280", "20.webp,2020.webp,dop.webp,yron.webp,Bo.webp", "no"))
cursor.execute(insert_request, ("Эмз", "Epic", "Вообще-то Эмз работает в морге у своего дяди Мортиса, но редко там появляется. Она слишком занята рекламой своего бренда лака для волос.", "7200", "1040", "21.webp,2121.webp,dop.webp,yron.webp,Emz.webp", "yes"))
cursor.execute(insert_request, ("Сту", "Epic", "За свою карьеру каскадёра Сту пережил столько ударов и падений и так надышался бензином, что просто удивительно, как он вообще держится на колёсах.", "6400", "1080", "222.webp,2222.webp,shit.png,yron.webp,Stu.webp", "yes"))
cursor.execute(insert_request, ("Пайпер", "Epic", "Пайпер мечтает открыть пекарню и торговать пирожными, печеньем и другими сладостями. Только не стоит спрашивать её о прошлом, иначе можно очутиться в духовке.", "4600", "3400", "233.webp,2323.webp,dop..webp,shit.png,Piper.webp", "yes"))
cursor.execute(insert_request, ("Пем", "Epic", "Пэм целыми днями сортирует мусор на свалке. Она отличный работник, но у неё совсем не остаётся времени на родную дочь Джесси.", "9600", "520", "244.webp,2424.webp,dop.webp,Pemmm.webp,Pem.webp, Pem.webp", "no"))
cursor.execute(insert_request, ("Френк", "Epic", "Фрэнк — добродушный великан, который днём работает помощником в морге, а ночью — диджеем в клубе. По нему заметно, что он не высыпается", "13400", "2320", "255.webp,2525.webp,hil.png,dop.webp,Frank.webp", "yes"))
cursor.execute(insert_request, ("Биби", "Epic", "Биби выглядит как хулиганка и ходит с битой наперевес. Вообще-то она любит читать, но никогда не признается в этом, чтобы не испортить себе репутацию", "9600", "2800", "266.webp,2626.webp,dop.webp,yron.webp,Bibi.webp", "yes"))
cursor.execute(insert_request, ("Беа", "Epic", "Беа целыми днями наблюдает за разными букашками, представляя, как круто было бы понимать их язык... или даже быть одной из них", "5000", "1600-4400", "277.webp,2727.webp,shit.png,yron.webp,Bea.webp", "no"))
cursor.execute(insert_request, ("Нани", "Epic", "Нани была простой камерой видеонаблюдения, пока её не модифицировали, чтобы присматривать за Джесси. К сожалению, она не всегда успевает угнаться за подопечной", "4800", "1480", "Nani.webp, 288.webp,2828.webp,dop.webp,yron.webp", "yes"))
cursor.execute(insert_request, ("Эдгар", "Epic", "Эдгара бесит, что его никто не понимает, особенно мама, которая уверена, что это просто переходный возраст. Разве она не видит, что в его душе царит вечная тьма?!", "6600", "1080", "Edgar.webp,299.webp,2929.webp,dop.webp,yron.webp", "yes"))
cursor.execute(insert_request, ("Анджело", "Epic", "Купидон Анджело обернулся комаром и поселился на болоте. Он кружит по каналам в поисках гуляющих парочек, по привычке сражая их если не своим чарующим обаянием, то стрелами.", "6000", "4000", "angelo.webp,30.webp,3030.webp,dop.webp,yron.webp", "yes"))
cursor.execute(insert_request, ("Менди", "Epic", "Мэнди управляет магазином сладостей, облачившись в наряд конфетной королевы. Иногда она немного увлекается и ведёт себя, как настоящий деспот.", "5600", "2600", "mandy.webp,31.webp,3131.webp,shit.png,yron.png", "no"))
cursor.execute(insert_request, ("Коллет", "Epic", "У Колетт есть плакаты и фигурки всех бойцов Brawl Stars. Можно ли назвать её одержимой фанаткой? Да. Но окончательно ли она сошла с ума? Тоже да.", "6800", "1000", "collet.webp,32.webp,3232.webp,dop.webp,yron.webp", "yes"))
cursor.execute(insert_request, ("Ларри и Лори", "Epic", "Ларри и Лори — билетёры в парке Старр. Ларри любит правила за то, что они упрощают жизнь, а Лори просто любит усложнять жизнь другим. Они отличная команда.", "5600", "1400", "l2l.webp,333.webp,3333.webp,dop.webp,yron.webp", "no"))
cursor.execute(insert_request, ("Мейси", "Epic", "Мэйси работает координатором по технике безопасности, но на самом деле ей нравится рисковать. Иногда она как будто нарочно создаёт опасные ситуации...", "7200", "3000", "meisi.webp,34.webp,3434.webp,dop.webp,yron.webp", "yes"))
cursor.execute(insert_request, ("Белль", "Epic", "Белль — глава банды Золотой руки. Она не только охотится за наживой, но и пытается выяснить всю правду о парке Старр, чтобы добиться его закрытия.", "5200", "2080", "bell.webp,35.webp,3535.webp,yron.webp,shit,png", "yes"))
cursor.execute(insert_request, ("Берри", "Epic", "В кондитерской Мэнди вечно всё вверх дном, но Берри не спешит оттуда увольняться. Может показаться, что он ненавидит свою работу, но в конце смены на его лице появляется улыбка.", "5000", "1320", "berry.webp,36.webp,3636.webp,yron.webp,dop.webp", "yes"))
cursor.execute(insert_request, ("Грифф", "Epic", "«Грифф ведёт себя как успешный бизнесмен, но его магазин сувениров в шаге от банкротства, а сам он бегает от налоговых инспекторов.", "6800", "560", "grif.webp,37.webp,3737.webp,yron.webp,shit.png", "no"))
cursor.execute(insert_request, ("Бонни", "Epic", "Бонни переполняет безудержная и глубоко разрушительная энергия. Её главная мечта — чтобы ею выстрелили из пушки на Луну!", "9600", "2240", "bonni.webp,38.webp,3838.webp,yron.webp,dop.webp", "no"))
cursor.execute(insert_request, ("Пёрл", "Epic", "Вопреки всем ожиданиям, Перл удалось растопить суровые сердца Белль и Сэма своим душевным теплом. Да и кто устоит перед шоколадным печеньем?", "7800", "905", "perl.webp,39.webp,3939.webp,yron.webp,dop.webp", "yes"))
cursor.execute(insert_request, ("Гром", "Epic", "Гром — мощный здоровяк-охранник. Он боится лишь одного: что его уволят и ему придётся вернуться на работу в детском саду. Дети не знают пощады.", "5600", "2280", "grom.webp,40.webp,4040.webp,yron.webp,dop.webp", "no"))
cursor.execute(insert_request, ("Гейл", "Epic", "Гэйл ответственно относится к своим обязанностям по уборке снега вокруг зимнего отеля мистера П. и не прекращает работу, даже если на пути оказались гости", "7600", "560", "geyl.webp,41.webp,4141.webp,yron.webp,dop.webp", "yes"))
cursor.execute(insert_request, ("Лола", "Epic", "Лола умеет произвести на себя впечатление с порога. Она не стесняется устраивать скандалы, чтобы добиться своего, и гордится этим талантом!", "7600", "560 * 6", "lola.webp,42.webp,4242.webp,yron.webp,dop.webp", "no"))
cursor.execute(insert_request, ("Сем", "Epic", "Сэм — бывший фабричный рабочий, вступивший в банду Золотой руки. Он помогает Белль, прикрывая её во время ограблений!", "10800", "1600 * 2", "sem.webp,43.webp,4343.webp,yron.webp,dop.webp", "no"))
cursor.execute(insert_request, ("Хенк", "Epic", "Пусть Хэнк всего лишь креветка, но у него есть танк и благородная цель: вызволить всю морскую живность с рынков и кухонь мира. Повара, берегитесь!", "11200", "4200", "henk.webp,444.webp,4444.webp,yron.webp,hil.png", "no"))
cursor.execute(insert_request, ("Эш", "Epic", "Эш занимается самой грязной работой — уборкой парка. Мусорный бак служит ему доспехом, защищая от крысиных укусов и битого стекла, но не улучшает настроения.", "10800", "1600", "esh.webp,45.webp,4545.webp,yron.webp,dop.webp", "yes"))
cursor.execute(insert_request, ("Мортис", "Mythic", "Мортис мечтал о карьере гробовщика и по совместительству вампира, но его планам помешало то, что в парке Старр никто не умирает.", "7600", "2000", "mortis.webp,46.webp,4646.webp,,mort_myt,dop.webp", "yes"))
cursor.execute(insert_request, ("Тара", "Mythic", "Карты Тары предрекают тебе суровые испытания! Но не волнуйся, у неё полно волшебных талисманов, которые она готова продать по выгодной цене.", "6200", "960 * 3", "tara.webp,47.webp,4747.webp,yron.webp,dop.webp", "yes"))
cursor.execute(insert_request, ("Джин", "Mythic", "Глядя на Джина, многие видят просто маленького человечка в странном костюме. Но им стоит повнимательнее присмотреться к его чайнику. Или это лампа?..", "7200", "2000", "jin.webp,48.webp,4848.webp,shit.png,dop.webp", "yes"))
cursor.execute(insert_request, ("Макс", "Mythic", "Макс полна сил благодаря энергетическим напиткам. Она первая спешит на помощь, если кто-то в беде... Но часто так разгоняется, что пробегает мимо.", "6600", "640 * 4", "max.webp,49.webp,4949.webp,yron.webp,dop.webp", "yes"))
cursor.execute(insert_request, ("Мистер Пи", "Mythic", "Директор отеля мистер П. постоянно кричит и подгоняет своих сотрудников. Это не помогает — они вообще не понимают, что он говорит.", "6800", "1520", "mp.webp,50.webp,5050.webp,petm.webp,dop.webp", "no"))
cursor.execute(insert_request, ("Спраут", "Mythic", "Спраут выглядит как милый робот, помогающий Розе в «Биокуполе», но на самом деле это инкубатор на колёсах для странного розового семечка.", "6000", "2080", "sprout.webp,51.webp,5151.webp,zaryad_supera.webp,shit.png", "yes"))
cursor.execute(insert_request, ("Байрон", "Mythic", "Байрон изобрёл множество микстур и эликсиров, как целебных, так и ядовитых. Но в основном ядовитых. Да что уж там, почти все его зелья — страшная отрава.", "4800", "710 * 3", "byron.webp,52.webp,5252.webp,shit.png,dop.webp", "no"))
cursor.execute(insert_request, ("Сквик", "Mythic", "Скуик — ходячий сгусток позитива, обожающий своего создателя Гавса. Все его любят, по крайней мере, пока не поймут, что он сделан из собачьих слюней.", "7200", "2320", "sqwick.webp,53.webp,5353.webp,shit.png,dop.webp", "yes"))
cursor.execute(insert_request, ("Лу", "Mythic", "Лу — робот-автомат с мороженным, у которого никто ничего не покупает. Возможно, ему стоило бы спуститься с заснеженного горного пика, куда не добраться пешком.", "6400", "880 * 3", "lu.webp,54.webp,5454.webp,shit.png,dop.webp", "yes"))
cursor.execute(insert_request, ("Р-Т", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Лили", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Базз", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Бастер", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Мелоди", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Мико", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Мо", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Гавс", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Грей", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Виллоу", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Отис", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Даг", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Джанет", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Джу Джу", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Ева", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Кленси", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Фенг", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Чак", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Чарли", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Спайк", "Legendary", "", "", "", "yes"))
cursor.execute(insert_request, ("Ворон", "Legendary", "", "", "", "yes"))
cursor.execute(insert_request, ("Леон", "Legendary", "", "", "", "yes"))
cursor.execute(insert_request, ("Сенди", "Legendary", "", "", "", "yes"))
cursor.execute(insert_request, ("Амбер", "Legendary", "", "", "", "no"))
cursor.execute(insert_request, ("Вольт", "Legendary", "", "", "", "yes"))
cursor.execute(insert_request, ("Честер", "Legendary", "", "", "", "no"))
cursor.execute(insert_request, ("Драко", "Legendary", "", "", "", "no"))
cursor.execute(insert_request, ("Кит", "Legendary", "", "", "", "no"))
cursor.execute(insert_request, ("Кендзи", "Legendary", "", "", "", "no"))

text = cursor.execute("SELECT * FROM brawler")
print(text.fetchall())