import sqlite3


connection = sqlite3.connect("database.sqlite")
cursor= sqlite3.Cursor(connection)


request = ("CREATE TABLE IF NOT  EXISTS brawler"
           "(id INTEGER PRIMARY KEY AUTOINCREMENT,"
           "name VARCHAR(255),"
           "rares VARCHAR(255),"
           "description VARCHAR(255),"
           "hp INTEGER,"
           "yron INTEGER,"
           "hypercharge VARCHAR(255))")
cursor.execute(request)

insert_request = ("INSERT INTO brawler" "(name, rares, description, hp, yron, hypercharge) VALUES (?, ?, ?, ?, ?, ?)")

cursor.execute(insert_request, ("Шелли", "common", "Шелли — идеальный рейнджер. Она ответственная, выносливая и непревзойдённо обращается с ружьём, и ей непонятно, как Кольт перетянул всё внимание на себя", "7400", "600", "yes"))
cursor.execute(insert_request, ("Нита", "rare", "Нита — совсем малышка, но рвётся в бой с недетской яростью! Её шапка в виде плюшевого мишки как бы намекает: не будите спящего медведя", "8000", "1920", "yes"))
cursor.execute(insert_request, ("Кольт", "rare", "Кольт — настоящая звезда парка Старр! Его стиль, обаяние и трюки с пистолетами покорят любого (за исключением Шелли)", "5600", "720", "yes"))
cursor.execute(insert_request, ("Булл", "rare", "Булл уже не такой бесшабашный, как в юности, но это ещё не значит, что он не наваляет любому, кто явно напрашивается", "10000", "880", "yes"))
cursor.execute(insert_request, ("Брок", "rare", "Брок — геймер и тролль. Вообще-то он романтичный интроверт, но ради победы он готов выйти из зоны комфорта", "5400", "2320", "yes"))
cursor.execute(insert_request, ("Эль Примо", "rare", "Эль Примо всегда в центре внимания, и он это просто обожает! Публика в восторге от него, а вот коллеги – не очень", "12000", "760", "yes"))
cursor.execute(insert_request, ("Барли", "rare", "Барли — робот для приготовления напитков и разговоров с посетителями. Он помешан на чистоте, и это сразу поймёт любой, кто прольёт напиток на его барную стойку", "4800", "1600", "yes"))
cursor.execute(insert_request, ("Поко", "rare", "Поко верит в чудотворную силу музыки и так любит свою гитару, что ни на минуту не прекращает играть. Даже когда его очень просят", "7400", "1520", "yes"))
cursor.execute(insert_request, ("Роза", "rare", "Роза одинаково увлекается и ботаникой, и боксом. Она обожает свой сад, но если какое-то растение обнаглеет, то получит и по вершкам, и по корешкам", "10000", "920", "yes"))
cursor.execute(insert_request, ("Джесси", "superrare", "Джесси — изобретательница-вундеркинд. Она мастерит оружие и гаджеты из хлама, чтобы доказать своей матери Пэм, что может постоять за себя", "6000", "2120", "yes"))
cursor.execute(insert_request, ("Диномайк", "superrare", "Динамайк — старый шахтёр и золотоискатель, который обожает всё взрывать. Ничто не радует его так, как запах дыма и грохот камней!", "5600", "1600", "yes"))
cursor.execute(insert_request, ("Тик", "superrare", "Тик хвостиком ходит за Пенни и участвует во всех её затеях. Единственное, что он умеет — это взрывать всё вокруг, но другого от него обычно и не требуется", "4400", "1280", "yes"))
cursor.execute(insert_request, ("8-бит", "superrare", "8-БИТ — игровой автомат, ненавидящий игроков. Всё потому, что однажды кто-то разозлился из-за проигрыша и украл один из его пистолетов", "10000", "640", "yes"))
cursor.execute(insert_request, ("Рико", "superrare", "Рико — совершенно точно самый настоящий межгалактический охотник за головами, а не автомат со жвачкой, который пытается круто выглядеть", "5600", "640", "yes"))
cursor.execute(insert_request, ("Дэррил", "superrare", "Дэррил пошёл в пираты, потому что устал работать, но теперь ему приходится вкалывать ещё больше, защищая корабль. Какая ирония", "10600", "480", "yes"))
cursor.execute(insert_request, ("Пенни", "superrare", "Пенни не разбирается в старых картах и морских легендах. Быть пираткой для неё означает палить из пушек и брать всё, что приглянулось!", "6400", "1960", "yes"))
cursor.execute(insert_request, ("Карл", "superrare", "Карл — робот-шахтёр, который без ума от камней и горных пород, а в последнее время серьёзно увлёкся изучением кристаллов!", "8000", "1480", "no"))
cursor.execute(insert_request, ("Джеки", "superrare", "Джеки любит рассказывать всякие байки из своей шахтёрской жизни, не стесняясь в выражениях. К счастью, шум отбойного молотка заглушает ругательства", "10000", "2480", "yes"))
cursor.execute(insert_request, ("Гас", "superrare", "Малыш Гас такой бледный, что его часто принимают за привидение. Впрочем, ему это нравится, ведь он обожает всё жуткое и сверхъестественное", "6400", "2240", "no"))
cursor.execute(insert_request, ("Бо", "Epic", "Бо уже долгое время выживает в джунглях. Впечатляет, учитывая, что у него при себе нет ничего, кроме игрушек из магазина сувениров", "7200", "1280", "no"))
cursor.execute(insert_request, ("Эмз", "Epic", "Вообще-то Эмз работает в морге у своего дяди Мортиса, но редко там появляется. Она слишком занята рекламой своего бренда лака для волос.", "7200", "1040", "yes"))
cursor.execute(insert_request, ("Сту", "Epic", "За свою карьеру каскадёра Сту пережил столько ударов и падений и так надышался бензином, что просто удивительно, как он вообще держится на колёсах.", "6400", "1080", "yes"))
cursor.execute(insert_request, ("Пайпер", "Epic", "Пайпер мечтает открыть пекарню и торговать пирожными, печеньем и другими сладостями. Только не стоит спрашивать её о прошлом, иначе можно очутиться в духовке.", "4600", "3400", "yes"))
cursor.execute(insert_request, ("Пем", "Epic", "Пэм целыми днями сортирует мусор на свалке. Она отличный работник, но у неё совсем не остаётся времени на родную дочь Джесси.", "9600", "520", "no"))
cursor.execute(insert_request, ("Френк", "Epic", "Фрэнк — добродушный великан, который днём работает помощником в морге, а ночью — диджеем в клубе. По нему заметно, что он не высыпается", "13400", "2320", "yes"))
cursor.execute(insert_request, ("Биби", "Epic", "Биби выглядит как хулиганка и ходит с битой наперевес. Вообще-то она любит читать, но никогда не признается в этом, чтобы не испортить себе репутацию", "9600", "2800", "yes"))
cursor.execute(insert_request, ("Беа", "Epic", "Беа целыми днями наблюдает за разными букашками, представляя, как круто было бы понимать их язык... или даже быть одной из них", "5000", "1600-4400", "no"))
cursor.execute(insert_request, ("Нани", "Epic", "Нани была простой камерой видеонаблюдения, пока её не модифицировали, чтобы присматривать за Джесси. К сожалению, она не всегда успевает угнаться за подопечной", "4800", "1480", "yes"))
cursor.execute(insert_request, ("Эдгар", "Epic", "", "", "", "yes"))
cursor.execute(insert_request, ("Анджело", "Epic", "", "", "", "yes"))
cursor.execute(insert_request, ("Менди", "Epic", "", "", "", "no"))
cursor.execute(insert_request, ("Коллет", "Epic", "", "", "", "yes"))
cursor.execute(insert_request, ("Ларри и Лори", "Epic", "", "", "", "no"))
cursor.execute(insert_request, ("Мейси", "Epic", "", "", "", "yes"))
cursor.execute(insert_request, ("Белль", "Epic", "", "", "", "yes"))
cursor.execute(insert_request, ("Берри", "Epic", "", "", "", "no"))
cursor.execute(insert_request, ("Грифф", "Epic", "", "", "", "no"))
cursor.execute(insert_request, ("Бонни", "Epic", "", "", "", "no"))
cursor.execute(insert_request, ("Пёрл", "Epic", "", "", "", "yes"))
cursor.execute(insert_request, ("Гром", "Epic", "", "", "", "no"))
cursor.execute(insert_request, ("Гейл", "Epic", "", "", "", "yes"))
cursor.execute(insert_request, ("Лола", "Epic", "", "", "", "no"))
cursor.execute(insert_request, ("Сем", "Epic", "", "", "", "no"))
cursor.execute(insert_request, ("Хенк", "Epic", "", "", "", "no"))
cursor.execute(insert_request, ("Эш", "Epic", "", "", "", "no"))
cursor.execute(insert_request, ("Мортис", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Тара", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Джин", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Макс", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Мистер Пи", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Спраут", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Байрон", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Сквик", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Лу", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Р-Т", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Лили", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Базз", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Бастер", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Мелоди", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Мико", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Мо", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Гавс", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("Грей", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Виллоу", "Mythic", "", "", "", "no"))
cursor.execute(insert_request, ("Отис", "Mythic", "", "", "", "yes"))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))
cursor.execute(insert_request, ("", "", "", "", "", ""))

text = cursor.execute("SELECT * FROM brawler")
print(text.fetchall())